columns:
  Restaurant_ID: int
  Restaurant_Name: category
  Country_Code: int
  City: category
  Address: category
  Locality: category
  Locality_Verbose: category
  Longitude: float
  Latitude: float
  Cuisines: category
  Currency: category
  Has_Table_booking: category
  Has_Online_delivery: category
  Is_delivering_now: category
  Switch_to_order_menu: category
  Price_range: int
  Votes: int
  Average_Cost_for_two: int
  Rating: float

numerical_columns:
  - Restaurant_ID
  - Country_Code
  - Longitude
  - Latitude
  - Price_range
  - Votes
  - Average_Cost_for_two
  - Rating
  - Currency
  - Has_Table_booking
  - Has_Online_delivery
  - Is_delivering_now
  - Switch_to_order_menu



categorical_columns:
  - Restaurant_Name
  - City
  - Address
  - Locality
  - Locality_Verbose
  - Cuisines




target_column: Rating





  



